inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable

require:
  - rubocop-rspec

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: True
Lint/StructNewOverride:
  Enabled: True
Style/ExponentialNotation:
  Enabled: True
Style/HashEachMethods:
  Enabled: True
Style/HashTransformKeys:
  Enabled: True
Style/HashTransformValues:
  Enabled: True
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: True
Lint/DeprecatedOpenSSLConstant:
  Enabled: True
Lint/MixedRegexpCaptureTypes:
  Enabled: True
Style/RedundantRegexpCharacterClass:
  Enabled: False
Style/RedundantRegexpEscape:
  Enabled: False
Style/SlicingWithRange:
  Enabled: True
Style/AccessorGrouping:
  Enabled: True
Style/BisectedAttrAccessor:
  Enabled: True
Style/RedundantAssignment:
  Enabled: True
Style/RedundantFetchBlock:
  Enabled: True
