# frozen_string_literal: true
# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'image_scraper'
  s.version = '0.1.8'

  if s.respond_to? :required_rubygems_version=
    s.required_rubygems_version = Gem::Requirement.new('>= 0')
  end
  s.authors = ['John McAliley']
  s.description = 'Simple utility to pull image urls from web page'
  s.email = 'john.mcaliley@gmail.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.document',
    'Gemfile',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'image_scraper.gemspec',
    'lib/image_scraper.rb',
    'lib/image_scraper/client.rb',
    'lib/image_scraper/railtie.rb',
    'lib/image_scraper/util.rb'
  ]
  s.homepage = 'http://github.com/charlotte-ruby/image_scraper'
  s.licenses = ['MIT']
  s.require_paths = ['lib']
  s.rubygems_version = '1.8.24'
  s.summary = 'Simple utility to pull image urls from web page'
  s.test_files = [
    'test/helper.rb',
    'test/test_image_scraper.rb'
  ]

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('css_parser', ['>= 0'])
      s.add_runtime_dependency('nokogiri', ['>= 0'])
      s.add_runtime_dependency('rails', ['>= 0'])
      s.add_development_dependency('bundler', ['~> 1.0.0'])
      s.add_development_dependency('jeweler', ['~> 1.5.2'])
      s.add_development_dependency('rcov', ['>= 0'])
      s.add_development_dependency('shoulda', ['>= 0'])
      s.add_runtime_dependency('nokogiri', ['>= 0'])
      s.add_runtime_dependency('nokogiri', ['>= 0'])
    else
      s.add_dependency('bundler', ['~> 1.0.0'])
      s.add_dependency('css_parser', ['>= 0'])
      s.add_dependency('jeweler', ['~> 1.5.2'])
      s.add_dependency('nokogiri', ['>= 0'])
      s.add_dependency('nokogiri', ['>= 0'])
      s.add_dependency('nokogiri', ['>= 0'])
      s.add_dependency('rails', ['>= 0'])
      s.add_dependency('rcov', ['>= 0'])
      s.add_dependency('shoulda', ['>= 0'])
    end
  else
    s.add_dependency('nokogiri', ['>= 0'])
    s.add_dependency('nokogiri', ['>= 0'])
    s.add_dependency('rails', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
    s.add_dependency('shoulda', ['>= 0'])
  end
  s.metadata['rubygems_mfa_required'] = 'true'
end
