#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'

require './lib/image_scraper'

url = ARGV[0].to_s

image_scraper = ImageScraper::Client.new(url)

scraped_urls = image_scraper.image_urls.sort.uniq

puts scraped_urls * "\n" if scraped_urls.count
