#!/usr/bin/env ruby
# frozen_string_literal: true

require 'image_scraper'

url = ARGV[0].to_s

unless url.length.positive?
  puts 'usage: image_scraper <url>'
  exit 1
end

image_scraper = ImageScraper::Client.new(url)
scraped_urls = image_scraper.image_urls

puts scraped_urls * "\n" if scraped_urls.count.positive?
