name: release
on:
  push:
    branches: [master]
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GEM_NAME: image_scraper
    steps:
      - uses: googleapis/release-please-action@v5.0.0
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v7
      - name: install ruby
        if: "${{ steps.release.outputs.release_created }}"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: bundle
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          bundle config unset --local deployment
          bundle
      - name: publish gem
        if: "${{ steps.release.outputs.release_created }}"
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: "${{secrets.RUBYGEMS_API_KEY}}"
          github_token: "${{secrets.GITHUB_TOKEN}}"
